DATA:
  data_name: 3dcompat
  classes:  44 # 275 for fine, 43 for coarse, add background as 0
  aug: False
  voxelSize: 0.05
  categories: 43 # 43 classes
  style: True
  mat: 14 # 13 material classes, add background as 0
  com: 10
  view_type: -1
  
MODEL:
  use_2d_classifier: True
  use_3d_classifier: False
  viewNum: 8
  weight_2d: 0.1
  arch: bpnet # bpnet
  layers_2d: 34
  arch_3d: MinkUNet18A
  sync_bn_2d: False
  ignore_label: 0
  
TRAIN:
  train_gpu: [0,1,2,3,4,5,6,7] #[ 0,1,2,3]
  workers: 12 # data loader workers
  batch_size: 80  # batch size for training
  batch_size_val: 64   # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  loop: 5
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1463
  print_freq: 50
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

Distributed:
  dist_url: tcp://127.0.0.1:6784
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  split: test  # split in [train, val and test]
  val_benchmark: True
  test_workers: 0
  test_gpu:  [0,1]
  test_batch_size: 24

  model_path:
  save_folder:
  test_repeats: 1
